### ISSUE TITLE
Check boxes in training form need to be more visible

### ISSUE THREAD

**Issue by CrispinF** [exeGesIS-SDM/esdm-mojowebsite-skin#1]
See form far down this page (for example): https://www.esdm.co.uk/arcgis-training-courses 
The checkboxes are too faint. I'm pretty sure this used to be fine - not sure what's changed!

**Comment by hefin1** [comment]
![image](https://user-images.githubusercontent.com/13196509/44160334-0434eb80-a0b2-11e8-9595-914e9aadffa5.png)

Butched them up a little, bigger with a 1px border

![image](https://user-images.githubusercontent.com/13196509/44160509-87eed800-a0b2-11e8-9401-c3c0f13e4cec.png)

**Comment by hefin1** [comment]
Over to @CrispinF to test and sign off.

**Comment by CrispinF** [comment]
Fine
