### ISSUE TITLE
Issue with date picker on asv and project review forms

### ISSUE THREAD

**Issue by epennifold** [exeGesIS-SDM/esdm-mojowebsite-skin#24]
From Griff:

While reviewing the online ASV feedback (https://www.esdm.co.uk/annual-service-visit-feedback) and project review forms (https://www.esdm.co.uk/project-client-evaluation) for ISO9001 purposes, we noticed that there is a small issue with the date picker, as shown below:

![image](https://user-images.githubusercontent.com/15983319/72433725-dfa2de80-3791-11ea-83b8-346701099573.png)

**Comment by CrispinF** [comment]
Could you @StewartBellamy ? Check with Joe whether his recent work deployed/pushed.
