### ISSUE TITLE
Sub-menu is behind content 

### ISSUE THREAD

**Issue by CrispinF** [exeGesIS-SDM/esdm-mojowebsite-skin#3]
Visit this page as anonymous user https://www.esdm.co.uk/mapinfo-training-courses
Then expand the sub-menu of Training. The sub-menu items fall behind the scrolling content of "What our training customers say...".  This is using an HTML Content instance in "slide show" mode, which seems to be affecting z-order. 
Can we fix this without having to edit that content? e.g. by increasing z-order of the sub-menu?

**Comment by hefin1** [comment]
Yep, it's as you say the slideshow is dynamically updating the z-index and opacity css properties. Workaround is to increase the z-index of the submenu.  Added rule:

`.AspNet-Menu.static {z-index:30;}`

I added a higher z-index initially but the top horizontal menu pop-out were appearing under the side menu.  Tested IE, Edge and Chrome.

**Comment by hefin1** [comment]
Over to @CrispinF to test and sign off.

**Comment by CrispinF** [comment]
Fine
