### ISSUE TITLE
Search bar expands over navbar links

### ISSUE THREAD

**Issue by AlexHorridge-ESDM** [exeGesIS-SDM/esdm-mojowebsite-skin#4]
Clicking the search icon on the navbar results in the search bar expanding over the download link on the navbar. It is also moving the navbar bottom border up and down during the transition from icon to search bar.

![image](https://user-images.githubusercontent.com/33840501/43638488-0220468c-9711-11e8-9744-ff60a56bae28.png)

![image](https://user-images.githubusercontent.com/33840501/43638770-f4cd26fc-9711-11e8-8289-734aefc2e276.png)

**Comment by hefin1** [comment]
Bit of a hard one to nail down.  If it doesn't expand over the ESDM menu then it would have to go over the right handside potentially it would might go outside of the viewport, unless we make it aware!

But I've stop the transition moving the bar.

**Comment by hefin1** [comment]
Over to @CrispinF to test and sign off

**Comment by CrispinF** [comment]
@hefin1 the menu image above seems to be from the Office site - correct? In that site, using the search now makes all page content drift upwards a few pixels. This doesn't happen on ESDM.co.uk.
??

**Comment by CrispinF** [comment]
Hefin hadn't deployed the new skin to the office site, so ignore previous comment.
