### ISSUE TITLE
Improve bullet styles in html content

### ISSUE THREAD

**Issue by StewartBellamy** [exeGesIS-SDM/esdm-mojowebsite-skin#5]
Find a nicer bullet style:

![image](https://user-images.githubusercontent.com/10956017/44097497-d00a64a2-9fd5-11e8-9b00-3e35d493d746.png)

**Comment by hefin1** [comment]
I'm seeing Multi-line bulleted lists being mis-aligned [https://www.esdm.co.uk/hidden-catch](https://www.esdm.co.uk/hidden-catch)

![image](https://user-images.githubusercontent.com/13196509/44402622-421a8f80-a54a-11e8-963c-69f444737e56.png)

**Comment by hefin1** [comment]
Updated style, margin attribute

`.htmlmodule .modulecontent li:before {
    font-family: 'fontawesome';
	font-size: 18px;
    content: '\f05d';
    margin: 0 0.8em 0 -1.7em;
    color: #888888;
}`


![image](https://user-images.githubusercontent.com/13196509/44403012-354a6b80-a54b-11e8-9994-91fb6e067b14.png)

**Comment by hefin1** [comment]
It appears Blog isn't using the updated bullet style

[https://www.esdm.co.uk/gower-hedgerow-mapping](https://www.esdm.co.uk/gower-hedgerow-mapping.
)
Need to widen the CSS selector to catch blog posts.

**Comment by hefin1** [comment]
Found one example of ordered list picking up the bullet style.  Need to exclude order lists from using the bullets

[https://www.esdm.co.uk/gradient-and-accessibility-mapping](https://www.esdm.co.uk/gradient-and-accessibility-mapping)

**Comment by hefin1** [comment]
Fixed above.

Over to @CrispinF to test and sign off

**Comment by CrispinF** [comment]
Nice bullet style.
