### ISSUE TITLE
The Logo is not centred in mobile viewport

### ISSUE THREAD

**Issue by hefin1** [exeGesIS-SDM/esdm-mojowebsite-skin#6]
The logo is not centred and is getting pushed under the hamburger menu.

Below Chrome emulated screengrab of Samsung S5

![image](https://user-images.githubusercontent.com/13196509/44403261-e18c5200-a54b-11e8-9055-6d0b254c8d7a.png)

**Comment by hefin1** [comment]
Updated CSS to make the logo smaller on mobile and centre

![image](https://user-images.githubusercontent.com/13196509/44415912-73ef1e80-a569-11e8-8a92-ac6ede0ab3e3.png)

**Comment by hefin1** [comment]
Over to @CrispinF to test sign off

**Comment by CrispinF** [comment]
Fine
