### ISSUE TITLE
Poor Page Layout on mojoportal-web-site-example page

### ISSUE THREAD

**Issue by hefin1** [exeGesIS-SDM/esdm-mojowebsite-skin#7]
Our page mojoportal-web-site-examples, layout is poor, mobile view is not great either.

[https://www.esdm.co.uk/mojoportal-web-site-examples](https://www.esdm.co.uk/mojoportal-web-site-examples)

Could rename this 'CMS Website Examples' omitting the 'mojoPortal' and we could then include some CloudScribe examples or create CloudScribe page(s) to promote our CS capabilities and sites.

Crispin let me know if you would like me to look at this.

**Comment by epennifold** [comment]
Agreed - this page isn't a great example of our CMS skills.
